name: Fibonacci
on: push

jobs:
  build:
    name: Correr la accion de fibonacci
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: ./fibonacci
          with:
            N_INPUT: 9